### ISSUE TITLE
Sometimes jobs don't have tests

### ISSUE THREAD

**Issue by eddycharly** [mheap/pin-github-action#108]
When reusing workflows, you can have jobs like this:
```yaml
jobs:
  job:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reuse.yaml
    with:
      // ...
    secrets:
      // ...
```

In this case, there is an error:
```
No job.steps found
```

Those jobs should be considered valid ones and just skipped.
