### ISSUE TITLE
Tool changes `pull_request:` to `pull_request: null`

### ISSUE THREAD

**Issue by banool** [mheap/pin-github-action#111]
Hey, given this workflow file:
```
name: "Check SDK examples"
on:
  pull_request:
  push:
    branches:
      - devnet

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.GIT_SHA }}
```

If you run the tool like this:
```
pin-github-action workflows/check-sdk-examples.yaml
```

It changes the file to this:
```
name: "Check SDK examples"
on:
  pull_request: null
  push:
    branches:
      - devnet

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.GIT_SHA }}
```

How can I make it not change `pull_request:` to `pull_request: null`? It does the same thing for `workflow_dispatch:`.

I'd also like the tool to not change the formatting of my yaml, but that's another issue.
