### ISSUE TITLE
Only last action is being pinned from YAML file

### ISSUE THREAD

**Issue by gladykov** [mheap/pin-github-action#180]
_Cannot attach YAML file in Github , so will paste inline._

When running `DEBUG="pin-github-action*" pin-github-action .github/workflows/js.yaml` only last action `devops-infra/action-pull-request` is pinned . If I remove last action ( `devops-infra/action-pull-request` ), only action before will get pinned (`tj-actions/verify-changed-files`). `pin-github-action` is finding correct SHAs .

System: Linux

```
  pin-github-action:extract-actions Processing workflow +0ms
  pin-github-action:find-ref-on-github Fetching ref tags/v1 +0ms
  pin-github-action:find-ref-on-github [dorny/test-reporter] Error fetching ref: Not Found +615ms
  pin-github-action:find-ref-on-github [dorny/test-reporter] ERROR: Could not find repo. It may be private, or it may not exist +1ms
  pin-github-action:find-ref-on-github Fetching ref heads/v1 +0ms
  pin-github-action:find-ref-on-github [dorny/test-reporter] Ref is a commit. Found sha. +609ms
  pin-github-action:find-ref-on-github Fetching ref tags/v3 +0ms
  pin-github-action:find-ref-on-github [SonarSource/sonarqube-scan-action] Ref is a commit. Found sha. +616ms
  pin-github-action:find-ref-on-github Fetching ref tags/v4 +0ms
  pin-github-action:find-ref-on-github [codecov/codecov-action] Ref is a commit. Found sha. +592ms
  pin-github-action:find-ref-on-github Fetching ref tags/v18 +0ms
  pin-github-action:find-ref-on-github [tj-actions/verify-changed-files] Ref is a commit. Found sha. +604ms
  pin-github-action:find-ref-on-github Fetching ref tags/v0.5.5 +0ms
  pin-github-action:find-ref-on-github [devops-infra/action-pull-request] Ref is a commit. Found sha. +586ms
```

js.yaml:

```
name: Workflow A
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Jobs-B:
    name: Job B
    runs-on: ubuntu-latest
    steps:
      - name: Hello World B from TestRepo2
        run: echo "Hello World B"
      - name: Dump GitHub context A
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Publish M unit test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: M unit tests report
          path: mmc/junit.xml
          reporter: jest-junit
          #           max-annotations: '0'  # https://github.com/dorny/test-reporter/issues/131
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v3
        if: ${{(github.event_name == 'pull_request' && github.base_ref == 'main' && always()) || (github.event_name == 'push' && always()) || (github.event_name == 'workflow_dispatch' && always())}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        if: ${{(github.event_name == 'pull_request' && github.base_ref == 'main' && always()) || (github.event_name == 'push' && always()) || (github.event_name == 'workflow_dispatch' && always())}}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Check if there are changes to files
        uses: tj-actions/verify-changed-files@v18
        id: verify-changed-files
        with:
          read-gitignore: true
      - name: Create PR
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.PAT }}
          source_branch: ${{ env.BRANCH_NAME }}
          target_branch: main
          title: ${{ env.PR_TITLE }}

```
