### ISSUE TITLE
Support quoted values for `uses`

### ISSUE THREAD

**Issue by pravindahal** [mheap/pin-github-action#183]
It seems that if the uses part is quoted, it does not work.

```
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
```

Expected:
```
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # pin@v4
```

Actual (no change):
```
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
```
