### ISSUE TITLE
Comments on line after github actions gets overwritten

### ISSUE THREAD

**Issue by Hofer-Julian** [mheap/pin-github-action#196]
## Description

If you have a github actions yaml and would like to pin it's actions, problems appear if there's a comment after a line with a defined action.

## Reproducible example

Run `pnpx pin-github-action .github/workflows/lint.yml` on

```yaml
name: CI
on:
  push:

jobs:
  # Checks for dependencies that are not used in the codebase
  cargo-machete:
    name: Cargo Machete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  # Checks for duplicate version of package
  cargo-vendor:
    name: Cargo Vendor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
```

This will lead to:

```yaml
name: CI
on:
  push:

jobs:
  # Checks for dependencies that are not used in the codebase
  cargo-machete:
    name: Cargo Machete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

  # v4
  cargo-vendor:
    name: Cargo Vendor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
```

Notice that the comment above `cargo-vendor` is gone and no comment is next to `actions/checkout`
