### ISSUE TITLE
Documentation - using the docker image

### ISSUE THREAD

**Issue by dannystaple** [mheap/pin-github-action#208]
It would be handy if the readme specified how to use the docker image. This is an example in a github workflows context:

```yaml
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Run pin github action
        run: |
          docker run \
            --rm \
            -v ${{ github.workspace }}:/workflows \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_ACCESS_TOKEN }} \
            mheap/pin-github-action:3.3.1 .github/workflows

      - name: Create pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          title: "Build(deps): Secure GitHub action SHAs"
          base: main
          body: "This pull request was automatically generated to swap github version numbers for SHAs"
          branch: "auto/secure-github-actions"
          commit-message: "Build(deps): Secure GitHub action SHAs"
          labels: dependencies
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
```
